# Generated by Django 2.1.2 on 2020-01-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_activities', '0004_auto_20191121_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
